---
- name: Configure grafana repo in apt
  ansible.builtin.shell: |
    sudo apt-get install -y apt-transport-https software-properties-common wget
    sudo mkdir -p /etc/apt/keyrings/
    wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null
    echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

- name: Install grafana
  ansible.builtin.apt:
    name: grafana
    update_cache: yes

- name: Start grafana if not started
  ansible.builtin.service:
    name: grafana-server
    state: started
